builds:
  - skip: true
brews:
  - name: somafm
    homepage: "https://github.com/nicarl/somafm"
    tap:
      owner: nicarl
      name: homebrew-somafm
    commit_author:
      name: Nico Carl
      email: nicocarl@protonmail.com

release:
  prerelease: auto
  extra_files:
    - glob: ./somafm-build/**/*
    - glob: ./somafm-build/checksums.txt

universal_binaries:
  - replace: true
checksum:
  name_template: "checksums.txt"
