name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            env: GOOS=linux GOARCH=amd64
            file: somafm-${{ github.ref_name }}-linux-amd64
          - os: macos-latest
            file: somafm-${{ github.ref_name }}-darwin-amd64
            env: GOOS=darwin GOARCH=amd64
          - os: windows-latest
            file: somafm-${{ github.ref_name }}-windows-amd64.exe
            env: ""

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true

      - name: Install dependencies
        run: sudo apt-get install libasound2-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Build binary
        run: ${{ matrix.env }} go build -o ${{ matrix.file }} ./cmd/somafm.go
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.file }}

  homebrew-releaser:
    runs-on: ubuntu-latest
    name: homebrew-releaser
    steps:
      - name: Release to Homebrew tap
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: nicarl
          homebrew_tap: homebrew-somafm
          formula_folder: Formula
          github_token: ${{ secrets.HOMEBREW_PUBLISH_TOKEN }}
          commit_owner: nicarl
          commit_email: nicocarl@protonmail.com

          depends_on: |
            "go" => :build

          install: |
            (buildpath/"src/github.com/nicarl/somafm").install buildpath.children
                cd "src/github.com/nicarl/somafm" do
                  system "go", "build", "-o", bin/"somafm", "./cmd/somafm.go"
                end
          update_readme_table: true
          skip_commit: false
          debug: false
