name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Install dependencies
        run: sudo apt-get install libasound2-dev
      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --skip-publish --config .goreleaser-for-linux.yaml
        env:
          GITHUB-TOKEN: ${{ secrets.HOMEBREW_PUBLISH_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: somafm-linux
          path: dist/somafm*

  build-darwin-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --skip-publish --config .goreleaser-for-darwin.yaml
        env:
          GITHUB-TOKEN: ${{ secrets.HOMEBREW_PUBLISH_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: somafm-darwin
          path: dist/somafm*

  release:
    needs: [build-linux-binary, build-darwin-binary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Make directories
        run: |
          mkdir -p ./somafm-build/linux
          mkdir -p ./somafm-build/darwin
      - name: Download linux binaries
        uses: actions/download-artifact@v3
        with:
          name: somafm-linux
          path: ./somafm-build/linux
      - name: Download darwin binaries
        uses: actions/download-artifact@v3
        with:
          name: somafm-darwin
          path: ./somafm-build/darwin
      - name: Merge checksum file
        run: |
          cd ./somafm-build
          cat ./darwin/somafm*checksums.txt >> checksums.txt
          cat ./linux/somafm*checksums.txt >> checksums.txt
          rm ./darwin/somafm*checksums.txt
          rm ./linux/somafm*checksums.txt
      - name: Release
        uses: goreleaser/goreleaser-action@v3
        with:
          args: release --config .goreleaser-release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_PUBLISH_TOKEN }}
